project_name: hello
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: .github/workflows/dummy.go
    id: hello_dummy
    binary: hello
    hooks:
      post:
        - sh .github/workflows/post_build.sh
archives:
  - replacements:
      id: hello_archives
      darwin: darwin
      linux: linux
      amd64: x86_64
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - completions/**/*
brews:
  - name: hello
    description: "hello app"
    homepage: https://github.com/rvigo/homebrew-hello
    tap:
      owner: rvigo
      name: homebrew-hello
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    caveats: |
      In order to get hello completion, be sure that $(brew --prefix)/share/zsh/site-functions is present at $FPATH.
      If not add the following line to your ~/.zshrc:
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}
    install: |-
      bin.install "hello"
      zsh_completion.install "completions/zsh/hello.zsh" => "_hello"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: rvigo
    name: hello
  prerelease: auto
  draft: false
