project_name: hello
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: .github/workflows/dummy.go
    binary: hello
    hooks:
      post:
        - sh .github/workflows/post_build.sh
archives:
  - replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
brews:
  - name: hello
    description: "hello app"
    homepage: https://github.com/rvigo/homebrew-hello
    tap:
      owner: rvigo
      name: homebrew-hello
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: rvigo
    name: hello
  prerelease: auto
  draft: false
