name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        target: [
            x86_64-apple-darwin,
            # x86_64-unknown-linux-gnu,
            # aarch64-unknown-linux-gnu,
            aarch64-apple-darwin,
          ]
        include:
          - target: x86_64-apple-darwin
            os: macos
          # - target: x86_64-unknown-linux-gnu
          #   os: ubuntu
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu
          - target: aarch64-apple-darwin
            os: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: ${{ matrix.target }}
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.os == 'ubuntu' }}
          args: --release --bins --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/${{ matrix.target }}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.target }}
