name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        target:
          [
            x86_64-apple-darwin,
            x86_64-unknown-linux-gnu,
            aarch64-unknown-linux-gnu,
            aarch64-apple-darwin,
          ]
        include:
          - target: x86_64-apple-darwin
            os: macos
            compress: zip
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            compress: tar.gz
          - target: aarch64-unknown-linux-gnu
            os: ubuntu
            compress: tar.gz
          - target: aarch64-apple-darwin
            os: macos
            compress: zip

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: ${{ matrix.target }}
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.os == 'ubuntu' }}
          args: --release --bins --target ${{ matrix.target }}
      - name: Rename artifacts
        run: |
          mv target/${{ matrix.target }}/release/hello target/${{ matrix.target }}/release/hello-${{ matrix.target }}

      - name: Test
        if: ${{ matrix.os }} == 'macos'
        run: echo macos

      - name: Zip artifacts
        if: startsWith(${{ matrix.os }}, 'macos')
        run: zip hello-${{ matrix.target }}.zip target/${{ matrix.target }}/release/hello-${{ matrix.target }}

      - name: Tar artifacts
        if: ${{ matrix.os }} == 'ubuntu'
        run: tar -czvf hello-${{ matrix.target }}.tar.gz target/${{ matrix.target }}/release/hello-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hello-${{ matrix.target }}.${{ matrix.compress }}
          path: |
            target/${{ matrix.target }}/release/hello-${{ matrix.target }}.${{ matrix.compress }}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: hello-${{ matrix.target }}.${{ matrix.compress }}
          path: target/${{ matrix.target }}/release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/hello-${{ matrix.target }}.${{ matrix.compress }}
